### ISSUE TITLE
DEIMOS fcs images in dep_locate

### ISSUE THREAD

**Issue by jmader** [KeckObservatoryArchive/data-evaluation-and-processing#19]
dep_locate should find any DEIMOS fcs images that are associated with the instrument science files.  For all DEIMOS science files found, the fcs images recorded in the FITS header keyword FCSIMGFI should be added to the list of files to process and copied to the stage directory.

**Comment by mkb0517** [comment]
I broke the sorting up into two parts. First the program checks if the instrument is DEIMOS, then if it is, it gets the header value for FCSIMGFI. If the value is not empty and it is not a duplicate value, it appends the value to the presorted file as well as a list of values already used. This way it should prevent the same file from being added over and over. Once this section completes, it continues as normal checking the files as it did before.

**Comment by mkb0517** [comment]
I reopened the issue until it has been verified to be fixed.

**Comment by jmader** [comment]
Tested and works as expected.
