### ISSUE TITLE
[LRISBLUE] CCDGN00 vs. [LRIS] CCDGN04

### ISSUE THREAD

**Issue by esalvolucas** [KeckObservatoryArchive/data-evaluation-and-processing#298]
Scripts in question:
set_ccdtype in instr_lris.py
ccdtype_lris.pro

When INSTRUME == 'LRISBLUE', the IDL version seems to push the 4th value in the gainblue and rnblue arrays to the front, and assign that to CCDGN00 and CCDRN00 instead of CCDGN04 and CCDRN04. Is this a feature or a bug? If it _is_ a feature, why does it do this? There's no commenting on why this is done this way in the IDL.

LRIS has CCDGN/RN0[1-4], while LRISBLUE has CCDGN/RN0[0-3]...

**Comment by jmader** [comment]
Looks like this is a bug in the IDL source, but looks good in Python with the use of the offset.

The number in these keywords refers to the amp location (AMPLOC keyword in the image headers).  This value is 0 to 3 for LRISBLUE and 1 to 4 for LRISRED.  I'm not sure why the difference, but the keyword description says it's the value at that AMPLOC.
