### ISSUE TITLE
WAVEBLUE/RED/CNTR dichroic cutoff (lambda_lris.pro)

### ISSUE THREAD

**Issue by esalvolucas** [KeckObservatoryArchive/data-evaluation-and-processing#301]
For LR.20190830.79965.fits, it seems like the dichroic min/max is being ignored on the IDL side. Seems like a bug, based on the explanation JoshW gave of how this is supposed to work. Wavelength range is [3500,9000], should be cut to [6800,9000] based on a 680 dichroic...

**Comment by jmader** [comment]
DICHNAME should be used to do the cutoff.

**Comment by esalvolucas** [comment]
@jmader it is, but the dichroic is in nm and everything else is in angstroms
