### ISSUE TITLE
SIG2NOIS

### ISSUE THREAD

**Issue by esalvolucas** [KeckObservatoryArchive/data-evaluation-and-processing#305]
Doesn't seem the same as HIRES, doesn't spit out numbers anywhere close to what IDL says

**Comment by jmader** [comment]
Not sure what this line does:
spaflux = convolve(spaflux,Box1DKernel(3))

The HIRES S/N does not have this and uses:
maxflux = np.max(spaflux)
minflux = np.min(spaflux)

**Comment by esalvolucas** [comment]
It's from the IDL code
`spaflux = smooth(spaflux,3)`
